### PR TITLE
Remove p1_utils dependency

### PR DESCRIPTION
**Pull request by suexcxine**
A little duplication over a dependency.

### CODE REVIEW

**Comment by badlop** [comment]
Initially get_so_path was implemented here, but was moved to p1_utils in https://github.com/processone/iconv/commit/13069b15dacd24df62015ae93db9c59d408dfc0c

Now you propose to revert back that, copy get_so_path from p1_utils, and remove p1_utils dependency. 

What is your motivation to try to avoid p1_utils dependency? What benefit does that provide?

**Comment by suexcxine** [comment]
We don't need that dependency for only one function, it's overkill.

And there is also a proverb that says "A little copying is better than a little dependency."

**Comment by 1st8** [comment]
The dependency on p1_utils 1.0.21 instead of 1.0.23 currently prevents me from compiling with OTP24, so I would agree with removing the dependency.

Can this MR be released to hex.pm please?

**Comment by badlop** [comment]
Yes, iconv 1.0.13 is just tagged and published in hex.pm

**Comment by 1st8** [comment]
Wow that was fast :) 
Thank you very much @badlop !

Also big thanks to @suexcxine for the initiative to remove the dependency 👍

**Pull request merged**
